### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by smbiko** [smbiko/Love-running-#3]
In order to **anonymous feedback** as a **user**, I can **choose to hide my identity in the poll service**.

**Acceptance criteria**

- the option should be provided as a checkbox
- the checkbox should be "checked" by default
- the option should appear next to the submit button 
- After submitting the default submission confirmation should be adjusted to include the user name

**Task**

- [ ] Update the view : the poll design (HTML and CSS) to include the checkbox and to slow the name of the submitter.
- [ ] Create a new field in the model to track the username 
- [ ] Update the controller function 
- [ ] Update unit test scripts
- [ ] Test the functionality
